site_name: PfotenRegister Handbuch
theme:
  name: material
  language: de
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
   - scheme: default
     primary: teal         # z. B. 'indigo', 'green', 'deep orange' oder HEX
     accent: light blue
   - scheme: slate
     primary: teal
     accent: light blue
     toggle:
       icon: material/weather-night
       name: Dunkelmodus

nav:
  - Einführung: index.md

  - Nutzung der Plattform:
    - Admin-Bereich:
      - Dashboard: admin/dashboard.md
      - Berichte: admin/reports.md
      - Datenimport/-export: admin/data.md
      - Nutzerverwaltung:
        - Nutzer erstellen: admin/users/create.md
        - Nutzer bearbeiten: admin/users/edit.md
      - Einstellungen:
        - Allgemeine Einstellungen: admin/settings/pages.md
        - Feldsichtbarkeit & Erinnerungen: admin/settings/fields.md
        - Foodtags: admin/settings/tags.md

    - Erste Schritte: getting-started.md

    - Gäste verwalten:
      - Gäste ansehen: guests/view_all.md
      - Gast ansehen: guests/view_one.md
      - Gast registrieren: guests/create.md
      - Gast bearbeiten: guests/edit.md
      - Gast aktivieren/deaktivieren: guests/status.md
      - Gast löschen: guests/delete.md
      - Dokumente/Anhänge: attachments.md
      - Nachrichten: messages.md
    - Tiere verwalten:
      - Tier registrieren: animals/create.md
      - Tier bearbeiten: animals/edit.md
      - Tier aktivieren/deaktivieren: animals/status.md
      - Tier löschen: animals/delete.md
      - Tierliste: animals/list.md

    - Futterausgabe & Tagsystem:
      - Futterhinweis anlegen: feeding-notes/create.md
      - Tags verwalten: feeding-notes/tags.md
      - Futter ausgeben: feeding-notes/distribute.md
      - Futterausgabe bearbeiten: feeding-notes/edit.md

    - Zahlungen:
      - Zahlung erstellen: payments/create.md
      - Zahlung vormerken: payments/hold.md
      - Vormerkung bezahlen: payments/confirm.md
      - Gegenbuchung erstellen: payments/reversal.md
      - Zahlungsliste: payments/list.md

    - Glossar: glossary.md

  - Workflows:
    - Gast anlegen: workflows/create-guest.md
    - Tags anlegen und nutzen: workflows/tags-system.md
    - Futterausgabe durchführen: workflows/feeding.md
    - Zahlung erfassen: workflows/payments.md
    - Dokumente hochladen: workflows/attachments.md



meta:
  contact: admin@pfotenregister.com
